version: '3.9'
services:
  rldb:
        image: 'postgres:13.1-alpine'
        container_name: rldb
        environment:
            - POSTGRES_USER=dbusername                                     ### replace the DB-USERNAME with your desired USERNAME
            - POSTGRES_PASSWORD=dbusername                                ### replace the DB-PASSWORD with your desired PASSWORD
        volumes:
          - "./database_schema/init_rls.sql:/tmp/init_rls.sql"
          - "./database_schema/rldb:/var/lib/postgresql/data"
        ports:
          - "5431:5432"
  pgadmin:
      container_name: pgadmin4_container


      image: dpage/pgadmin4

      environment:
          - PGADMIN_DEFAULT_EMAIL=pgu@mail.com
          - PGADMIN_DEFAULT_PASSWORD=pgp
      ports:
          - "5050:80"


networks:
  default:
    driver: rl-net

  

